Repository Flow-Launcher/Flow.Launcher.Localization, pull requests merged in 2025-03, with the labels that each got.

#16 Use Remark comments to show example string
  Flow.Launcher.Localization.SourceGenerators/Localize/LocalizeSourceGenerator.cs
Labels: enhancement

#15 Resolve namespace prefix dynamically
  Flow.Launcher.Localization.SourceGenerators/Localize/LocalizeSourceGenerator.cs
Labels: bug

#17 Fix Index Issue for Format String & Add Culture Info When Need to Format
  Flow.Launcher.Localization.SourceGenerators/Localize/LocalizeSourceGenerator.cs
Labels: bug

#18 Add FLLUseDependencyInjection property group & Move all constants to Shared project
  Flow.Launcher.Localization.Analyzers/Flow.Launcher.Localization.Analyzers.csproj
  Flow.Launcher.Localization.Analyzers/Localize/ContextAvailabilityAnalyzer.cs
  Flow.Launcher.Localization.Analyzers/Localize/OldGetTranslateAnalyzerCodeFixProvider.cs
  Flow.Launcher.Localization.Shared/Constants.cs
  Flow.Launcher.Localization.Shared/Flow.Launcher.Localization.Shared.csproj
  Flow.Launcher.Localization.Shared/Helper.cs
  Flow.Launcher.Localization.SourceGenerators/Flow.Launcher.Localization.SourceGenerators.csproj
  Flow.Launcher.Localization.SourceGenerators/Localize/LocalizeSourceGenerator.cs
  Flow.Launcher.Localization.slnx
  Flow.Launcher.Localization/Flow.Launcher.Localization.csproj
  Flow.Launcher.Localization/build/Flow.Launcher.Localization.props
Labels: enhancement

#26 Add README.md & Add package info
  Flow.Launcher.Localization/Flow.Launcher.Localization.csproj
  README.md
Labels: bug

#29 Use FileVersion in publish.yml
  .github/workflows/publish.yml
Labels: bug

#30 Enable publish to NuGet
  .github/workflows/publish.yml
Labels: bug

#31 Bump and remove version on other projects
  Flow.Launcher.Localization.Analyzers/Flow.Launcher.Localization.Analyzers.csproj
  Flow.Launcher.Localization.Shared/Flow.Launcher.Localization.Shared.csproj
  Flow.Launcher.Localization.SourceGenerators/Flow.Launcher.Localization.SourceGenerators.csproj
  Flow.Launcher.Localization/Flow.Launcher.Localization.csproj
Labels: bug

#25 Support string.Format culture info parameter analyzer & code fixer
  Flow.Launcher.Localization.Analyzers/Localize/OldGetTranslateAnalyzer.cs
  Flow.Launcher.Localization.Analyzers/Localize/OldGetTranslateAnalyzerCodeFixProvider.cs
Labels: enhancement

#32 Tell users unused keys & Generate all strings
  Flow.Launcher.Localization.SourceGenerators/Localize/LocalizeSourceGenerator.cs
Labels: bug, enhancement

#23 Move PluginClassInfo & Add code regions
  Flow.Launcher.Localization.Analyzers/Localize/ContextAvailabilityAnalyzer.cs
  Flow.Launcher.Localization.Analyzers/Localize/ContextAvailabilityAnalyzerCodeFixProvider.cs
  Flow.Launcher.Localization.Shared/Classes.cs
  Flow.Launcher.Localization.Shared/Flow.Launcher.Localization.Shared.csproj
  Flow.Launcher.Localization.Shared/Helper.cs
  Flow.Launcher.Localization.SourceGenerators/Localize/LocalizeSourceGenerator.cs
Labels: enhancement
